plugins { id 'com.android.application' }

android {
    namespace 'com.fitquest.app'
    compileSdk 35
    
    buildFeatures {
    buildConfig true
}

    defaultConfig {
        applicationId 'com.fitquest.app'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.12.1'
}

configurations.all {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}
